apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /home/adam/kompose convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  type: LoadBalancer
  ports:
  - name: '8080'
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: gateway
status:
  loadBalancer: {
    }