apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/adam/kompose convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: grader-pascal
  name: grader-pascal
spec:
  replicas: 1
  strategy: {
    }
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: grader-pascal
    spec:
      containers:
      - env:
        - name: RABBIT_HOST
          value: rabbitmq
        - name: RABBIT_PASSWORD
          value: rabbitpw
        - name: RABBIT_USERNAME
          value: rabbituser
        - name: VERSION
          value: '3'
        image: juriad/grader-pascal
        name: grader-pascal
        resources: {
          }
      restartPolicy: Always
status: {
  }