apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/adam/kompose convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: processor-node
  name: processor-node
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: processor-node
    spec:
      containers:
      - name: processor-node
        env:
        - name: DOCKER_HOST
          value: localhost
        - name: DOCKER_IMAGE
          value: juriad/runner-node
        - name: DOCKER_TIMEOUT
          value: '10000'
        - name: RABBIT_HOST
          value: rabbitmq
        - name: RABBIT_PASSWORD
          value: rabbitpw
        - name: RABBIT_USERNAME
          value: rabbituser
        - name: VERSION
          value: '2'
        image: juriad/processor-node
        resources: {
          }
        volumeMounts:
        - mountPath: /var/lib/docker
          name: docker
        - mountPath: /solutions
          name: solutions
      - name: dind
        image: docker:stable-dind
        resources: {
          }
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/docker
          name: docker
        - mountPath: /solutions
          name: solutions
      restartPolicy: Always
      volumes:
      - name: docker
        emptyDir: {
          }
      - name: solutions
        emptyDir: {
          }
status: {
  }