apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/adam/kompose convert
    kompose.version: 1.5.0 (999278f)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbitpw
        - name: RABBITMQ_DEFAULT_USER
          value: rabbituser
        image: juriad/rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources: {
          }
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitdata
      restartPolicy: Always
      volumes:
      - name: rabbitdata
        persistentVolumeClaim:
          claimName: rabbitdata
status: {
  }